project:
  type: book
  output-dir: docs

book:
  title: "Clases Chile-Argentina"
  author: "Pablo Pérez-Ahumada, Daniela Olivares-Collío"
  date: today
  chapters:
    - index.qmd
    - 01-proce-data-conclat-cl.qmd
    # - 02-proce-data-conclat-ar.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: es
  pdf:
    documentclass: scrreprt

editor: visual

